# Generated by Django 3.2.6 on 2021-09-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Room name")),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Room number"
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("CONFIRMED", "Confirmed only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        help_text="Public means that users can join even if they are not logged in. Confirmed means that only users who are logged in and confirmed can join. Private means that only logged in users who you have granted access to can join.",
                        max_length=20,
                        verbose_name="Access type",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Prevents more users from joining.",
                        verbose_name="Locked",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Password"
                    ),
                ),
                (
                    "banned_users",
                    models.ManyToManyField(
                        related_name="banned_from", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "invited_users",
                    models.ManyToManyField(
                        related_name="invited_to", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
